language: node_js
sudo: false
node_js:
  - "8"
cache:
  - npm
  - directories:
      - ".ci/pull-request-check/connector"
matrix:
  include:
      - addons:
          chrome: stable
        env: TEST_CHROME="1"
        # Work-around for https://github.com/travis-ci/travis-ci/issues/8836
        sudo: required
script:
  - git diff -z --name-only $TRAVIS_COMMIT_RANGE *.js | xargs -0 npm run lint --
  - cd .ci && ./checkDeletedTxt.sh
  - [[ -n TRAVIS_PULL_REQUEST ]] && cd .ci/pull-request-check && ./check-pull-request.sh
